-- Run in Supabase SQL Editor before using the Godot client.
-- The publishable key is safe for clients only when these RLS policies remain enabled.

grant usage on schema public to anon, authenticated;

create table if not exists public.player_saves (
    user_id uuid primary key references auth.users(id) on delete cascade,
    username text not null default 'Đạo hữu',
    qi_realm text not null default 'Luyện Khí Kỳ',
    body_realm text not null default 'Bì Nhục Cảnh',
    power bigint not null default 0,
    stones bigint not null default 0,
    save_data jsonb not null default '{}'::jsonb,
    updated_at timestamptz not null default now()
);

alter table public.player_saves enable row level security;

create index if not exists player_saves_power_idx
    on public.player_saves (power desc);

drop policy if exists "players read own save" on public.player_saves;
create policy "players read own save"
    on public.player_saves for select to authenticated
    using ((select auth.uid()) = user_id);

drop policy if exists "players insert own save" on public.player_saves;
create policy "players insert own save"
    on public.player_saves for insert to authenticated
    with check ((select auth.uid()) = user_id);

drop policy if exists "players update own save" on public.player_saves;
create policy "players update own save"
    on public.player_saves for update to authenticated
    using ((select auth.uid()) = user_id)
    with check ((select auth.uid()) = user_id);

grant select, insert, update on public.player_saves to authenticated;

-- Only these public ranking fields are exposed; save_data remains private under RLS.
create or replace view public.public_leaderboard
with (security_invoker = false)
as
select
    user_id,
    username as name,
    qi_realm,
    body_realm,
    power,
    stones,
    'Đạo Hữu'::text as title
from public.player_saves;

grant select on public.public_leaderboard to anon, authenticated;

create table if not exists public.world_chat (
    id bigint generated by default as identity primary key,
    user_id uuid not null references auth.users(id) on delete cascade,
    username text not null,
    message text not null check (char_length(message) between 1 and 240),
    created_at timestamptz not null default now()
);

create index if not exists world_chat_created_at_idx
    on public.world_chat (created_at desc);

alter table public.world_chat enable row level security;

drop policy if exists "world chat is readable" on public.world_chat;
create policy "world chat is readable"
    on public.world_chat for select to anon, authenticated
    using (true);

drop policy if exists "authenticated players send world chat" on public.world_chat;
create policy "authenticated players send world chat"
    on public.world_chat for insert to authenticated
    with check ((select auth.uid()) = user_id);

grant select on public.world_chat to anon, authenticated;
grant insert on public.world_chat to authenticated;
grant usage, select on sequence public.world_chat_id_seq to authenticated;

create or replace function public.set_world_chat_author()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
    new.username := coalesce(
        nullif(auth.jwt() -> 'user_metadata' ->> 'display_name', ''),
        split_part(coalesce(auth.jwt() ->> 'email', 'Đạo hữu'), '@', 1)
    );
    return new;
end;
$$;

drop trigger if exists set_world_chat_author_before_insert on public.world_chat;
create trigger set_world_chat_author_before_insert
    before insert on public.world_chat
    for each row execute function public.set_world_chat_author();

-- Keep server-side chat history bounded as well as the client's 40-line display buffer.
create or replace function public.trim_world_chat()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
    delete from public.world_chat
    where id in (
        select id from public.world_chat
        order by id desc
        offset 500
    );
    return new;
end;
$$;

drop trigger if exists trim_world_chat_after_insert on public.world_chat;
create trigger trim_world_chat_after_insert
    after insert on public.world_chat
    for each row execute function public.trim_world_chat();

-- Enable Supabase Realtime INSERT events for the world chat table.
do $$
begin
    if exists (select 1 from pg_publication where pubname = 'supabase_realtime')
       and not exists (
           select 1 from pg_publication_tables
           where pubname = 'supabase_realtime'
             and schemaname = 'public'
             and tablename = 'world_chat'
       ) then
        alter publication supabase_realtime add table public.world_chat;
    end if;
end
$$;
