name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Build Godot APK
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Compile Godot APK
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_executable_download_url: "https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_linux.x86_64.zip"
          godot_export_templates_download_url: "https://github.com/godotengine/godot/releases/download/4.3-stable/Godot_v4.3-stable_export_templates.tpz"
          relative_project_path: ""
          archive_output: false
          export_debug: true
          use_preset_export_path: false

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CanKhonTuTien-APK
          path: |
            **/*.apk
